image: node:lts-alpine

pages:
  script:
    - npm ci
    # jsdoc does not handle the vscode imports, copy the src and use `sed` to replace the imported typedefs
    - cp -R src srcx
    - find ./srcx -name "*.js" -print0 | xargs -0 sed -i "s/@typedef {typeof import/@xtypedef {typeof import/g"
    - npm run docs
    - ls -al -R public
  artifacts:
    paths:
      - public
  only:
    - master
